In [4]:
import numpy as np
import os
import  matplotlib.image as mpimg
from scipy import misc
from PIL import Image
import matplotlib.pyplot as plt
plt.show()

In [3]:
#load data
path = "orl_faces/s2/2.pgm"
try:  
    img  = Image.open(path) 
except IOError: 
    print("fail")

fail


In [ ]:
#hàm convert image sang vector
def img_to_vector(filename):
    img  = Image.open(filename).resize((112, 92)) 
    img_vector = np.array(img).flatten()
    sz = img_vector.shape[0]
    return img_vector

In [ ]:
#hàm tiền xử lý: đọc ảnh từ tập dữ liệu
#đưa dữ liệu đọc được vào 2 mảng là train_set và test_set 
#train_set_number và test_set_number là id của những người trong tập train và test
def preprocess(dataset_dir = "./orl_faces"):
    train_set = []
    train_set_number = []
    test_set = []
    test_set_number = []
    for i in range(15):
        person_id = i+1
        for j in range(10):
            if j < 6 :
                path = dataset_dir + '/s'+str(person_id)+'/'+str(j+1)+'.pgm'
                img = img_to_vector(path).astype(np.int64) 
                train_set.append(img)
                train_set_number.append(person_id)
            else : 
                path = dataset_dir + '/s'+str(person_id)+'/'+str(j+1)+'.pgm'
                img = img_to_vector(path).astype(np.int64)
                test_set.append(img)
                test_set_number.append(person_id)
        
    train_set = np.array(train_set)
    train_set_number = np.array(train_set_number)
    test_set = np.array(test_set)
    test_set_number = np.array(test_set_number)
    return train_set.T, train_set_number, test_set.T, test_set_number

In [ ]:
train_set,train_set_number,test_set,test_set_number = preprocess()

In [ ]:
print(train_set)
print(train_set.shape)

[[ 48  59  39 ...  39 117  39]
 [ 49  62  42 ...  40 120  41]
 [ 47  61  51 ...  39 121  39]
 ...
 [ 47  34  27 ...  32  77  39]
 [ 46  34  27 ...  34  76  38]
 [ 46  33  29 ...  39  72  40]]
(10304, 90)


In [ ]:
print(train_set_number)
print(train_set_number.shape)

[ 1  1  1  1  1  1  2  2  2  2  2  2  3  3  3  3  3  3  4  4  4  4  4  4
  5  5  5  5  5  5  6  6  6  6  6  6  7  7  7  7  7  7  8  8  8  8  8  8
  9  9  9  9  9  9 10 10 10 10 10 10 11 11 11 11 11 11 12 12 12 12 12 12
 13 13 13 13 13 13 14 14 14 14 14 14 15 15 15 15 15 15]
(90,)


In [ ]:
print(test_set)
print(test_set.shape)

[[ 16  44  41 ...  45 120 120]
 [ 35  43  41 ...  41 120 120]
 [ 45  37  43 ...  39 120 122]
 ...
 [ 37  44  42 ...  71  74  73]
 [ 36  41  43 ...  23  75  75]
 [ 37  36  41 ...  37  80  76]]
(10304, 60)


In [ ]:
print(test_set_number)
print(test_set_number.shape)

[ 1  1  1  1  2  2  2  2  3  3  3  3  4  4  4  4  5  5  5  5  6  6  6  6
  7  7  7  7  8  8  8  8  9  9  9  9 10 10 10 10 11 11 11 11 12 12 12 12
 13 13 13 13 14 14 14 14 15 15 15 15]
(60,)


In [ ]:
#hàm tìm trung bình
def find_mean(arr):
    M = np.mean(arr, axis = 1)
    return M

In [ ]:
#tìm trung bình của ma trận tập train_set
M = find_mean(train_set)
print(M)

[87.51111111 91.07777778 92.58888889 ... 59.11111111 58.35555556
 58.23333333]


In [ ]:
#tại mỗi giá trị của ma trận tập train_set, ta lấy giá trị đó trừ cho
#giá trị trung bình vừa tìm được ở trên
def mean_normalization(arr):
    M = find_mean(arr)
    x_range = arr.shape[0]
    y_range = arr.shape[1]
    for i in range(x_range):
        for j in range(y_range):
            arr[i][j] -= M[i]
    return arr

In [ ]:
#A là ma trận sau khi thực hiện hàm mean_normalize
A = mean_normalization(train_set)
A = A
#print(A)

In [ ]:
print(A.shape)

(10304, 90)


In [ ]:
#nhân A với ma trận chỉnh vị của nó
L = np.dot(A.T, A)
print(L.shape)
print(L)

(90, 90)
[[11727307  4194490  6683989 ...   -23821 -3071337   248621]
 [ 4194490 23296794  7755626 ...   350283  -795440  1264478]
 [ 6683989  7755626 15911800 ...  -992690 -2771586   981391]
 ...
 [  -23821   350283  -992690 ... 10795373   565882  6505605]
 [-3071337  -795440 -2771586 ...   565882  8305035  -172163]
 [  248621  1264478   981391 ...  6505605  -172163 10386103]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(L)
# sort eigenvectors theo giá trị của eigenvalues
print("eigenvalues shape : ", eigenvalues.shape)
print("eigenvalues : ", eigenvalues)
print("eigenvectors shape : ", eigenvectors.shape)
print("eigenvectors : ", eigenvectors)

eigenvalues shape :  (90,)
eigenvalues :  [2.47127240e+08 1.88571579e+08 1.06082686e+08 1.00140743e+08
 7.66564555e+07 6.18354478e+07 4.81852242e+07 3.95228371e+07
 3.47722119e+07 2.89910366e+07 2.48267104e+07 2.08764699e+07
 2.00051121e+07 1.79737001e+07 1.67152706e+07 1.59973213e+07
 1.39400190e+07 1.39829934e+07 1.25274060e+07 1.22177124e+07
 1.06977647e+07 1.00379037e+07 9.48350162e+06 8.29103269e+06
 7.73518794e+06 7.06524088e+06 6.91380226e+06 6.87421432e+06
 6.51295894e+06 6.48203081e+06 6.10516300e+06 5.81054179e+06
 5.63957943e+06 5.17224045e+06 5.06241194e+06 7.63389103e+04
 4.90714380e+06 4.71870181e+06 4.48641290e+06 4.43855232e+06
 4.32861662e+06 4.10641925e+06 6.95821879e+05 3.94037648e+06
 4.01876811e+06 3.72422355e+06 3.69023253e+06 9.99945120e+05
 1.05438254e+06 3.58811833e+06 3.49345960e+06 3.44472223e+06
 3.41940801e+06 1.14552123e+06 1.15799330e+06 1.21456833e+06
 1.25573301e+06 1.27234992e+06 3.28009202e+06 3.22198937e+06
 3.10395595e+06 1.36840004e+06 1.39263399e+

In [ ]:
U = []
sz = L.shape[0] #L là kết quả thu được khi nhân A với A.T
#nhân ma trận A với eigenvectors có bậc nằm trong khoảng sz
#kết quả từng phép nhân đó được thêm vào ma trận U
for i in range(sz):
    U.append(np.dot(A,eigenvectors[:,i]))

U = np.array(U)
U = U.T
print(U.shape)
print(U)

(10304, 90)
[[ 119.52285413  -64.02921134  -41.87783606 ...   23.38498888
    40.20529137  -10.49139841]
 [ 157.52692856 -138.28564869  -28.50162529 ...    6.85043499
    10.4359597     3.42251783]
 [ 173.05874426 -163.87482997  -25.79257688 ...    2.46565233
    -0.20323549   12.02044124]
 ...
 [ -41.82917094  -40.09296523  -78.94334686 ...   14.38039674
    -5.24537964   14.67280743]
 [ -26.66860579  -46.92099288  -66.52558913 ...   17.16789561
    -6.46485104   16.92424866]
 [  -2.42317401  -57.20274448  -57.85261544 ...   18.58900217
    -5.35270376   22.26584086]]


In [ ]:
#weight_vector là kq khi nhân chỉnh vị của U và A
weight_vector = np.dot(U.T, A)
print(weight_vector.shape)
print(weight_vector)

(90, 90)
[[ -2428375.74199202 -25063250.60619882 -23870270.71387946 ...
     906508.05287782   5923170.14052308  -9242839.46859596]
 [ -5494829.7158517  -37561097.43225766 -10058927.14806259 ...
   13597017.10850819  -1862846.92406132  11265682.51362844]
 [ 18325054.41057583  13525361.08393978  17928439.64324552 ...
    -417916.1239171   -3339577.89779013    492383.70978795]
 ...
 [   281105.32517653   -284636.57309796   -203251.91052953 ...
    -171215.32646557    279694.80126659   -580260.42936954]
 [   -96583.77455222   -192686.89874817   -108599.84596647 ...
    -254860.73918091    110668.26776897    148304.21643895]
 [   -51725.89728851   -299584.63416815    174804.11074535 ...
    -185108.7406542     443288.54864473    481292.62761833]]


In [ ]:
#tính overall mean bằng cách tính mean của ma trận weight vừa tính
overall_mean = np.mean(weight_vector, axis = 1)
overall_mean = overall_mean.reshape(overall_mean.shape[0],1)
print(overall_mean.shape)

(90, 1)


In [ ]:
#tìm within class Sw
#tìm mean cho từng class riêng lẻ
#số class là 15 (vì tập dữ liệu có 15 người)
SW = np.zeros([90,90])
for i in range(15):
    ind = i * 6
    V = weight_vector[:,ind:ind+6]
    mean_local = np.mean(V, axis = 1)
    mean_local = mean_local.reshape(mean_local.shape[0],1)
    mean = np.repeat(mean_local, 6,axis = 1)
    diff = V - mean
    variance = np.dot(diff, diff.T)
    SW = SW + variance

In [ ]:
#tìm between class Sb
SB = np.zeros([90,90])
print(variance.shape)
for i in range(15):
    j = i+6
    V = weight_vector[:,i:j]
    mean_local = np.mean(V, axis = 1)
    mean_local = mean_local.reshape(mean_local.shape[0],1)
    diff = mean_local - overall_mean
    sigma = np.dot(diff, mean_local.T)
    SB = SB  + sigma

(90, 90)


In [ ]:
#finding the criterion function
#maximises between class (Sb) và minimizes within class (Sw)
J = np.dot(np.linalg.pinv(SW), SB)
print(J.shape)

(90, 90)


In [ ]:
#tìm eigenvalues và eigenvectors của ma trận J
eigenval, eigenvec = np.linalg.eig(J)
fisher_faces = np.dot(eigenvec.T, weight_vector)
print(fisher_faces.shape)

(90, 90)


In [ ]:
#Bắt đầu công đoạn test
#thực hiện tương tự như tập train_set
x_range = test_set.shape[0]
y_range = test_set.shape[1]
print(M)
print(test_set)
for i in range(x_range):
    for j in range(y_range):
        test_set[i][j] -= M[i]
print(test_set.shape)
print(test_set)

[87.51111111 91.07777778 92.58888889 ... 59.11111111 58.35555556
 58.23333333]
[[ 16  44  41 ...  45 120 120]
 [ 35  43  41 ...  41 120 120]
 [ 45  37  43 ...  39 120 122]
 ...
 [ 37  44  42 ...  71  74  73]
 [ 36  41  43 ...  23  75  75]
 [ 37  36  41 ...  37  80  76]]
(10304, 60)
[[-71 -43 -46 ... -42  32  32]
 [-56 -48 -50 ... -50  28  28]
 [-47 -55 -49 ... -53  27  29]
 ...
 [-22 -15 -17 ...  11  14  13]
 [-22 -17 -15 ... -35  16  16]
 [-21 -22 -17 ... -21  21  17]]


In [ ]:
weight_vector_test = np.dot(U.T, test_set)
print(weight_vector_test.shape)
print(weight_vector_test)

(90, 60)
[[-1.65685549e+07 -2.97139328e+07 -2.30519021e+07 ...  2.32267557e+06
  -5.08124314e+05  7.16963417e+06]
 [-1.85998564e+07 -1.58021693e+07 -2.98786330e+07 ...  1.36447921e+07
   1.30940027e+06 -3.91965017e+06]
 [ 1.77043510e+07  4.61872923e+06  3.61955749e+06 ...  1.00388106e+06
  -3.08896873e+06 -4.48360409e+06]
 ...
 [-1.02958716e+05  1.14122138e+05 -2.05210857e+05 ...  2.24738674e+05
   6.55102939e+04 -8.59359133e+04]
 [ 7.89346415e+03 -1.01434976e+05 -1.00567738e+05 ...  2.80706097e+04
   4.07583239e+04 -6.93032348e+04]
 [-9.29409113e+04  5.58287172e+03 -1.48434079e+05 ... -1.52501285e+05
   1.15647774e+05 -7.51193974e+04]]


In [ ]:
projected_fisher_faces = np.dot(eigenvec.T, weight_vector_test)
print(projected_fisher_faces.shape)

(90, 60)


In [ ]:
#finding the norm between each projected_fisher_faces with that of fisher_faces and then finding the best match
validation = []
count = 0
for i in range(60) : 
    ith_wv = projected_fisher_faces[:,i]
    ans = 0
    index = 0
    for j in range(90):
        jth_wv = fisher_faces[:,j]
        diff = ith_wv - jth_wv
        diff = np.absolute(diff)
        sm = np.sum(diff)
        if ans == 0 :
            ans = sm
            index = j
        else :
            if sm < ans:
                ans = sm
                index = j
    if train_set_number[index] == test_set_number[i]:
        count = count + 1
        validation.append(1)
    else:
        validation.append(0)

In [ ]:
print(validation)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
print("accuracy = ", (count*100)/60, "%")

accuracy =  95.0 %
